default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password:
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: universities_management_api_development

test:
  <<: *default
  database: universities_management_api_test

production:
  <<: *default
  database: universities_management_api_production
